language: python
sudo: false

install:
  - pip install --upgrade pip
  - pip install --upgrade tox
  - ./scripts/update_tox_deps.sh

script:
  - tox -e py27
  - tox -e py34
  - tox -e lint
  - tox -e docs

after_success:
  - tox -e coveralls

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/virtualenv/python2.7.9/lib/python2.7/site-packages
    - ${HOME}/virtualenv/python2.7.9/bin
    - ${TRAVIS_BUILD_DIR}/.tox
