language: python
sudo: false

install:
  - pip install --upgrade pip tox
  - pip install --upgrade numpy Sphinx sympy

script:
  - tox -e docs
  - .tox/docs/bin/python -c 'import sys; print sys.executable'

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/virtualenv/python2.7.9/lib/python2.7/site-packages
    - ${HOME}/virtualenv/python2.7.9/bin
