language: python
sudo: false

before install:
  - mkdir -p ${HOME}/.cache/py-base
  - export PYTHONUSERBASE=${HOME}/.cache/py-base

install:
  - pip install --upgrade pip
  - pip install --user --upgrade matplotlib numpy Sphinx

script:
  - make docs

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/.cache/py-base
