language: python
sudo: false

install:
  - pip install --upgrade pip
  - pip install --upgrade tox

script:
  - .tox/py27/bin/pip install --upgrade --requirement=requirements.txt
  - tox -e py27
  - .tox/py34/bin/pip install --upgrade --requirement=requirements.txt
  - tox -e py34
  - tox -e lint
  - .tox/docs/bin/pip install --upgrade --requirement=requirements.txt
  - tox -e docs

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/virtualenv/python2.7.9/lib/python2.7/site-packages
    - ${HOME}/virtualenv/python2.7.9/bin
    - ${TRAVIS_BUILD_DIR}/.tox
