language: python
sudo: false

install:
  - pip install --upgrade pip
  - pip install --upgrade tox

script:
  - tox -e docs

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/virtualenv/python2.7.9/lib/python2.7/site-packages
    - ${HOME}/virtualenv/python2.7.9/bin
    - ${TRAVIS_BUILD_DIR}/.tox
