language: python
sudo: false

install:
  - pip install --upgrade pip
  - pip install --upgrade matplotlib numpy Sphinx

script:
  - sphinx-build -W -b html -d docs/_build/doctrees docs docs/_build/html

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/virtualenv/python2.7.9/lib/python2.7/site-packages
    - ${HOME}/virtualenv/python2.7.9/bin
