language: python
sudo: false

before_install:
  - export PYTHONPATH=${PYTHONPATH}:$(pwd)

install:
  - pip install --upgrade pip
  - pip install --upgrade matplotlib numpy Sphinx

script:
  - ./update_docs.sh

cache:
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/virtualenv/python2.7.9/lib/python2.7/site-packages
    - ${HOME}/virtualenv/python2.7.9/bin
